name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker://pandoc/core:3.5
        with:
          args: "--help" # gets appended to pandoc command

      - uses: docker://pandoc/latex:3.5
        with:
          args: >-  # allows you to break string into multiple lines
            --output=KotB.pdf
            KEEP.md
            OUTSIDE.md
            # RUMORS.md
            CAVES-A.md
            CAVES-B.md
            CAVES-C.md
            CAVES-D.md
            CAVES-E.md
            CAVES-F.md
            CAVES-G.md
            CAVES-H.md
            CAVES-I.md
            CAVES-J.md
            CAVES-K.md
            ITEMS.md
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./KotB.pdf
          asset_name: KotB.pdf
          asset_content_type: application/pdf