name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Get Pandoc Version
        run: pandoc --version

      - name: Get Pandoc Help
        run: pandoc --help

      - name: compile with pandoc
        run: |
          pandoc --verbose --output=KotB.pdf \
          KEEP.md \
          OUTSIDE.md \
          CAVES-A.md \
          CAVES-B.md \
          CAVES-C.md \
          CAVES-D.md \
          CAVES-E.md \
          CAVES-F.md \
          CAVES-G.md \
          CAVES-H.md \
          CAVES-I.md \
          CAVES-J.md \
          CAVES-K.md \
          ITEMS.md

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: KotB.pdf
          path: KotB.pdf

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ./KotB.pdf
      #     asset_name: KotB.pdf
      #     asset_content_type: application/pdf